export const SELECT_EPISODE = 'SELECT_EPISODE';
export const SEND_MAIL_REQUEST = "SEND_MAIL_REQUEST";
export const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS";
export const SEND_MAIL_FAILED = "SEND_MAIL_FAILED";


